# Generated by Django 5.2.7 on 2025-10-10 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclutamiento', '0003_alter_vacante_departamento_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Recibida', 'Recibida'), ('En Revisión', 'En Revisión'), ('Entrevista', 'Entrevista'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Recibida', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.vacante')),
            ],
            options={
                'unique_together': {('candidato', 'vacante')},
            },
        ),
    ]
