# Generated by Django 5.2.7 on 2025-10-07 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Puesto')),
                ('departamento', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('tipo_contrato', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Por Proyecto', 'Por Proyecto'), ('Remoto', 'Remoto')], default='Tiempo Completo', max_length=50)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=50)),
                ('salario_minimo', models.IntegerField(blank=True, null=True)),
                ('salario_maximo', models.IntegerField(blank=True, null=True)),
                ('fecha_cierre', models.DateField()),
                ('responsable_rh', models.CharField(max_length=100, verbose_name='Responsable RH')),
                ('descripcion', models.TextField(verbose_name='Descripción del Puesto')),
                ('requisitos', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
