# Generated by Django 5.2.7 on 2025-10-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='fecha_publicacion',
        ),
    ]
