# Generated by Django 5.2.7 on 2025-10-09 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0002_remove_vacante_fecha_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='departamento',
            field=models.CharField(choices=[('Tecnología E Informática', 'Tecnología E Informática'), ('Producto Digital', 'Producto Digital'), ('Artes Y Diseño', 'Artes Y Diseño'), ('Finanzas, Control De Gestión', 'Finanzas, Control De Gestión'), ('Data Y Business Intelligence', 'Data Y Business Intelligence'), ('Marketing', 'Marketing'), ('Logística, Compras Y Abastecimiento', 'Logística, Compras Y Abastecimiento'), ('Procesos, Estrategia Y Transformación', 'Procesos, Estrategia Y Transformación'), ('Legal', 'Legal'), ('Administración Y Secretariado', 'Administración Y Secretariado'), ('Sustentabilidad Y Medio Ambiente', 'Sustentabilidad Y Medio Ambiente'), ('Recursos Humanos', 'Recursos Humanos'), ('Comunicación y Periodismo', 'Comunicación y Periodismo'), ('Prevención De Riesgos', 'Prevención De Riesgos'), ('Producción Y Manufactura', 'Producción Y Manufactura'), ('Inmobiliaria', 'Inmobiliaria')], max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Opcional.', max_length=15, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('P', 'Prefiero no decirlo')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Opcional.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
